// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG55KG31U-GOf4xpcSDItH5ct0Grw2V_Y',
    appId: '1:121944115603:web:07ce4bae8ebd4464f9c066',
    messagingSenderId: '121944115603',
    projectId: 'plantinha-390e3',
    authDomain: 'plantinha-390e3.firebaseapp.com',
    storageBucket: 'plantinha-390e3.appspot.com',
    measurementId: 'G-KBESLGX9B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs_4ekMSivcRBR3QyIBaIfPKg9VLzGpgk',
    appId: '1:121944115603:android:2b5503cab1f28a58f9c066',
    messagingSenderId: '121944115603',
    projectId: 'plantinha-390e3',
    storageBucket: 'plantinha-390e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1p15WZdjE6lpfi61S9_NyiEh2eqOop_0',
    appId: '1:121944115603:ios:905bc075cf39cd31f9c066',
    messagingSenderId: '121944115603',
    projectId: 'plantinha-390e3',
    storageBucket: 'plantinha-390e3.appspot.com',
    androidClientId: '121944115603-76i7f3m2f21m899qsmao6nhfqshng4sj.apps.googleusercontent.com',
    iosClientId: '121944115603-42o0p4uvj96mc8llbvogckiqj8e5sdbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoPlantaRealidadeAumentada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1p15WZdjE6lpfi61S9_NyiEh2eqOop_0',
    appId: '1:121944115603:ios:905bc075cf39cd31f9c066',
    messagingSenderId: '121944115603',
    projectId: 'plantinha-390e3',
    storageBucket: 'plantinha-390e3.appspot.com',
    androidClientId: '121944115603-76i7f3m2f21m899qsmao6nhfqshng4sj.apps.googleusercontent.com',
    iosClientId: '121944115603-42o0p4uvj96mc8llbvogckiqj8e5sdbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoPlantaRealidadeAumentada',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG55KG31U-GOf4xpcSDItH5ct0Grw2V_Y',
    appId: '1:121944115603:web:0d7102d841df278af9c066',
    messagingSenderId: '121944115603',
    projectId: 'plantinha-390e3',
    authDomain: 'plantinha-390e3.firebaseapp.com',
    storageBucket: 'plantinha-390e3.appspot.com',
    measurementId: 'G-2BTNT34T01',
  );

}