// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmOb_pNVSO22dsxnFBfIYaMwaolP5BlmQ',
    appId: '1:366617342728:web:77e2821801731070e872bd',
    messagingSenderId: '366617342728',
    projectId: 'planta-ar',
    authDomain: 'planta-ar.firebaseapp.com',
    storageBucket: 'planta-ar.appspot.com',
    measurementId: 'G-7DTCQH6WC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-52tigVVTIQmYrlGwWc2XSHK1Y0ueKpI',
    appId: '1:366617342728:android:f9d5b9f1446f56e0e872bd',
    messagingSenderId: '366617342728',
    projectId: 'planta-ar',
    storageBucket: 'planta-ar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH-t0CCSj09rVEo5wi_eq4fuyQ_1JFGhE',
    appId: '1:366617342728:ios:3ca927b8316bc042e872bd',
    messagingSenderId: '366617342728',
    projectId: 'planta-ar',
    storageBucket: 'planta-ar.appspot.com',
    iosBundleId: 'com.example.projetoPlantaRealidadeAumentada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH-t0CCSj09rVEo5wi_eq4fuyQ_1JFGhE',
    appId: '1:366617342728:ios:3ca927b8316bc042e872bd',
    messagingSenderId: '366617342728',
    projectId: 'planta-ar',
    storageBucket: 'planta-ar.appspot.com',
    iosBundleId: 'com.example.projetoPlantaRealidadeAumentada',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmOb_pNVSO22dsxnFBfIYaMwaolP5BlmQ',
    appId: '1:366617342728:web:7bd1a2aee2b5ff9de872bd',
    messagingSenderId: '366617342728',
    projectId: 'planta-ar',
    authDomain: 'planta-ar.firebaseapp.com',
    storageBucket: 'planta-ar.appspot.com',
    measurementId: 'G-LZ3LEW8FS1',
  );

}